apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 1
     maxSurge: 0%
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: hastartdocker/webcentos:v3
        livenessProbe:
          tcpSocket:
            port: 8000
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8000
        volumeMounts:
          - name: app
            mountPath: /app
      initContainers:
        - name: html-gen
          image: busybox:musl
          command: ['sh', '-c', 'wget -O- https://bit.ly/otus-k8s-index-gen | sh']
          volumeMounts:
            - name: app
              mountPath: /app
      volumes:
        - name: app
          emptyDir: {}
