apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: carol:getwatchlist
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: getwatchlist
subjects:
- kind: ServiceAccount
  name: carol
  namespace: prometheus

