apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dave:norights
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: no-rights
subjects:
- kind: ServiceAccount
  name: dave
  namespace: kube-system

