apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dane:admin
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
- kind: ServiceAccount
  name: dane
  namespace: dev

